name: ramp
channels:
  - conda-forge
dependencies:
  - numpy
  - pyyaml
  - psycopg2
  - sqlalchemy
  - boto3
  - psutil
  - cloudpickle
  - gitpython
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-backend/zipball/master
    - https://api.github.com/repos/pythonprofilers/memory_profiler/zipball/master

