name: ramp
channels:
  - conda-forge
dependencies:
  - numpy
  - pyyaml
  - psycopg2
  - sqlalchemy
  - boto3
  - memory_profiler
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-backend/zipball/master

